set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
 
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
 
# set-option -g default-shell "$SHELL"

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
 
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g status-left " #S "
 
# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
 
# Shift arrow to switch windows
# bind -n S-Left  previous-window
# bind -n S-Right next-window
 
# Shift Alt vim keys to switch windows
# bind -n C-[ previous-pane
# bind -n C-] next-window
 
set -g @catppuccin_flavour 'mocha'
 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-bind 's'

set -g @plugin 'fcsonline/tmux-thumbs'

set -g @extrakto_key 'space'
set -g @thumbs-key 'Tab'

# set -g @thumbs-command 'echo -n {} | pbcopy && tmux display-message "Coppied to clipboard!"'
#
set -g @thumbs-command 'echo -n {} | pbcopy'

run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux
TMUX_FZF_LAUNCH_KEY="a"
set-option -g default-command "$SHELL -l"
# set vi-mode
set-window-option -g mode-keys vi
# change [ to v key
bind-key -T prefix v copy-mode
# set system clipboard
# set-option -g default-command "reattach-to-user-namespace -l $SHELL"
# keybindings
# bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
# bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
 
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind r switch-client -T resize
bind -T resize h resize-pane -L 5 \; switch-client -T resize
bind -T resize j resize-pane -D 5 \; switch-client -T resize
bind -T resize k resize-pane -U 5 \; switch-client -T resize
bind -T resize l resize-pane -R 5 \; switch-client -T resize

# split windows
bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind q killp
unbind '"'
unbind %

run '~/.tmux/plugins/tpm/tpm'
