# ==========================
# General Settings
# ==========================

set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-command "$SHELL -l"
set -g mouse on

# Image passthrough support (for image.nvim)
set -gq allow-passthrough on
set -g visual-activity off

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Status bar adjustments
set-window-option -g status-left " #S "

# Enable vi mode keys
set-window-option -g mode-keys vi


# ==========================
# Prefix Key
# ==========================

# Change prefix from 'Ctrl+B' to 'Ctrl+Space'
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


# ==========================
# Keybindings
# ==========================

# Split windows
unbind '"'
unbind %
bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind q killp

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Pane resizing (Prefix + r, then h/j/k/l)
bind r switch-client -T resize
bind -T resize h resize-pane -L 5 \; switch-client -T resize
bind -T resize j resize-pane -D 5 \; switch-client -T resize
bind -T resize k resize-pane -U 5 \; switch-client -T resize
bind -T resize l resize-pane -R 5 \; switch-client -T resize

# Copy mode (vi)
bind-key -T prefix v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# ==========================
# Plugins & Configuration
# ==========================

# TPM & Sensible
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

# Theme (Catppuccin)
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @catppuccin_flavour 'mocha'

# Utilities
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Tmux FZF
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="a"

# Extrakto
set -g @plugin 'laktak/extrakto'
set -g @extrakto_key 'space'

# SessionX
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-bind 's'

# Tmux Thumbs
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @thumbs-key 'Tab'
set -g @thumbs-command 'echo -n {} | pbcopy'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
